on:

  ## Daily
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once per day
    - cron:  '0 2 * * *'

  ## Manually triggered
  workflow_dispatch:

  ## On Push and Pull Request (trial, just during the PR.. to be removed..)
  pull_request:

jobs:
  maven_test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      ## Checkout the current version of the code from the repo.
      - name: Checkout latest code
        uses: actions/checkout@v2

      ## Setup the specified version of Java (includes maven/gradle).
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      ## Given that the build matrix only specifies the major version (configurable), output the precise version used.
      - name: Echo exact java version being used
        run: java -version

      - name: Echo exact maven version being used
        run: mvn --version

      ## Use a cache to reduce the build/test times (avoids having to download dependencies on EVERY run).
      ### https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache test zips (/var/tmp)
        uses: actions/cache@v2
        with:
          path: /var/tmp/javaparser_bulkparsetest
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-javaparser_bulkparsetest-var-tmp

      - name: Cache test zips (/var)
        uses: actions/cache@v2
        with:
          path: /tmp/javaparser_bulkparsetest
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-javaparser_bulkparsetest-tmp


#      - name: Test with Maven (incl. slow tests)
#        run: ./run_bulk_tests.sh

      - name: Install JavaParser
        run: mvn -e install -DskipTests -Darguments=-DskipTests

      - name: Run bulk tests that do downloading
        run: mvn -e -pl javaparser-core-testing test -Dtest=BulkParseTest*
