name: Maven -- Build and test
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
#        os: [ubuntu-latest]
        jdk: [8,11,13]
#        jdk: [8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      # https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven (incl. slow tests)
        run: mvn -e -B test -P AlsoSlowTests
